services:
  api:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: payment.escaliagora.com.br
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: payment.escaliagora.com.br
      LETSENCRYPT_EMAIL: edujudici@gmail.com
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: payment_processor
      DB_USER: app
      DB_PASS: secret
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network
      - proxy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_processor
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      # ports:
      # - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp", "-psecret" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

networks:
  app-network:
  proxy:
    name: nginx-proxy
    external: true

volumes:
  db_data:
